ci: disable windows runner due to build issue
Style check failed with make command:
Run make style-lint
  make style-lint
  shell: C:\Program Files\Git\bin\bash.EXE --noprofile --norc -e -o pipefail {0}
  env:
    CI_NAME: Commit CI
    CI_BRANCH: develop
    JAVA_HOME: C:\hostedtoolcache\windows\Java_Temurin-Hotspot_jdk\17.0.9-9.1\x64
    JAVA_HOME_17_X64: C:\hostedtoolcache\windows\Java_Temurin-Hotspot_jdk\17.0.9-9.1\x64
    ANDROID_HOME: C:\Android\android-sdk
    ANDROID_SDK_ROOT: C:\Android\android-sdk
./gradlew spotlessCheck
'.' is not recognized as an internal or external command,
operable program or batch file.
make: *** [Makefile:17: spotlessCheck] Error 1
Error: Process completed with exit code 2.